Demo: ConvertPixelType.cpp
	g++ -g -o ConvertPixelType ConvertPixelType.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMVFGControl -lpthread

clean:
	rm ConverPixelType -rf
