Demo: GrabImage_Callback.cpp
	g++ -g -o GrabImage_Callback GrabImage_Callback.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMVFGControl -lpthread

clean:
	rm GrabImage_Callback -rf
