Demo: GrabImage_UserBuffer.cpp
	g++ -g -o GrabImage_UserBuffer GrabImage_UserBuffer.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMVFGControl -lpthread

clean:
	rm GrabImage_UserBuffer -rf
