# true 1 和 false 0 
width: 4096             #图像宽度, default 4096
height: 3000            #图像高度, default 3000
Offset_x: 0             #X方向偏置
Offset_y: 0             #Y方向偏置

FrameRateEnable: true   #使能 
FrameRate: 8            #帧率, from 1 - 8 (maximum)

ExposureAuto: false
ExposureTime: 8000      #For indoor environment, the idea time is around 4000 - 5000, depends on the indoor lighting level
# ExposureTime: 8000      #For outdoor environment, the idea time is around 2000 - 3000 , depends on the outdoor lighting level
AutoExposureTimeLowerLimit: 100
AutoExposureTimeUpperLimit: 8000

BalanceWhiteAuto: 1

Brightness: 100         # Image brightness, default 100

GainAuto: 2             #亮度的固定增益

CalibrateEnable: false

ResizeEnable: false
DestinationHeight: 640
DestinationWidth: 640

SaturationEnable: true
Saturation: 128          #饱和度
