# true 1 和 false 0 
width: 4096             #图像宽度, default 4096
height: 3000            #图像高度, default 3000
Offset_x: 0             #X方向偏置
Offset_y: 0             #Y方向偏置

FrameRateEnable: true   #使能 
FrameRate: 7           #帧率

# ExposureTime: 50000     #曝光时间
# ExposureAuto: true
ExposureAuto: true
AutoExposureTimeLowerLimit: 100
AutoExposureTimeUpperLimit: 16777

BalanceWhiteAuto: 1

Brightness: 75

GammaEnable: false
Gamma: 0.7              #伽马因子

GainAuto: 2             #亮度的固定增益

CalibrateEnable: false

ResizeEnable: false
DestinationHeight: 640
DestinationWidth: 640

SaturationEnable: false
Saturation: 128          #饱和度
