Demo: GrabMultipleCamera_Callback.cpp
	g++ -g -o GrabMultipleCamera_Callback GrabMultipleCamera_Callback.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMVFGControl -lpthread

clean:
	rm GrabMultipleCamera_Callback -rf
