Demo: Grab_Asynchronous.cpp
	g++ -g -m32 -o Grab_Asynchronous Grab_Asynchronous.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/32 -L$(MVCAM_COMMON_RUNENV)/32 -lMvCameraControl -lpthread -std=c++11
	

clean:
	rm Grab_Asynchronous -rf
